/**
 * Demo family seed data for in-app demos.
 * Each family has accounts + ~3 months of realistic transactions + goals.
 * Category names match the DEFAULT_CATEGORIES list in useCategories.
 */

export interface DemoAccount {
  name: string;
  type: "checking" | "savings" | "investment" | "bitcoin" | "credit";
  currency: string;
  institution: string;
  balance: string;
}

export interface DemoTxn {
  daysAgo: number;
  amount: string;
  currency: string;
  description: string;
  merchant?: string;
  category: string; // matches DEFAULT_CATEGORIES name
  account: string; // matches DemoAccount.name
  memo?: string;
  tags?: string[];
}

export interface DemoGoal {
  name: string;
  type: "save_up" | "pay_down";
  targetAmount: string;
  targetDate: string; // YYYY-MM-DD
  account: string;
}

export interface DemoFamily {
  id: string;
  name: string;
  tagline: string;
  description: string;
  emoji: string;
  accentColor: string;
  accounts: DemoAccount[];
  transactions: DemoTxn[];
  goals: DemoGoal[];
}

const today = new Date();
const date = (daysAgo: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString().slice(0, 10);
};

// ─── Family 1: The Nakamoto Family ────────────────────────────────────────────
// Bitcoin-native family. Dad is a software engineer, mom freelances design.
// They DCA into BTC monthly and use Lightning for small purchases.

const NAKAMOTO: DemoFamily = {
  id: "nakamoto",
  name: "The Nakamoto Family",
  tagline: "Bitcoin-native · 2 incomes · 2 kids",
  description:
    "Sato (software engineer) and Mei (freelance designer) have been stacking sats since 2019. They use Lightning for daily spending and cold storage for long-term savings.",
  emoji: "₿",
  accentColor: "#f59e0b",
  accounts: [
    {
      name: "Chase Checking",
      type: "checking",
      currency: "USD",
      institution: "Chase",
      balance: "8420.00",
    },
    {
      name: "Chase Savings",
      type: "savings",
      currency: "USD",
      institution: "Chase",
      balance: "24000.00",
    },
    {
      name: "Cold Storage",
      type: "bitcoin",
      currency: "BTC",
      institution: "Ledger",
      balance: "0.85000000",
    },
    {
      name: "Lightning Wallet",
      type: "bitcoin",
      currency: "BTC",
      institution: "Phoenix",
      balance: "0.00150000",
    },
  ],
  transactions: [
    // Income
    {
      daysAgo: 2,
      amount: "7500.00",
      currency: "USD",
      description: "Salary deposit",
      merchant: "TechCorp Inc",
      category: "Salary",
      account: "Chase Checking",
    },
    {
      daysAgo: 17,
      amount: "7500.00",
      currency: "USD",
      description: "Salary deposit",
      merchant: "TechCorp Inc",
      category: "Salary",
      account: "Chase Checking",
    },
    {
      daysAgo: 32,
      amount: "7500.00",
      currency: "USD",
      description: "Salary deposit",
      merchant: "TechCorp Inc",
      category: "Salary",
      account: "Chase Checking",
    },
    {
      daysAgo: 47,
      amount: "7500.00",
      currency: "USD",
      description: "Salary deposit",
      merchant: "TechCorp Inc",
      category: "Salary",
      account: "Chase Checking",
    },
    {
      daysAgo: 62,
      amount: "7500.00",
      currency: "USD",
      description: "Salary deposit",
      merchant: "TechCorp Inc",
      category: "Salary",
      account: "Chase Checking",
    },
    {
      daysAgo: 5,
      amount: "2200.00",
      currency: "USD",
      description: "Freelance invoice #47",
      merchant: "Studio Collective",
      category: "Freelance",
      account: "Chase Checking",
    },
    {
      daysAgo: 35,
      amount: "3100.00",
      currency: "USD",
      description: "Freelance invoice #46",
      merchant: "Apex Brand Co",
      category: "Freelance",
      account: "Chase Checking",
    },
    {
      daysAgo: 65,
      amount: "1800.00",
      currency: "USD",
      description: "Freelance invoice #45",
      merchant: "Maven Media",
      category: "Freelance",
      account: "Chase Checking",
    },
    // Bitcoin DCA
    {
      daysAgo: 3,
      amount: "-0.01000000",
      currency: "BTC",
      description: "Monthly DCA",
      merchant: "Swan Bitcoin",
      category: "DCA purchase",
      account: "Cold Storage",
      tags: ["bitcoin", "dca"],
    },
    {
      daysAgo: 33,
      amount: "-0.01000000",
      currency: "BTC",
      description: "Monthly DCA",
      merchant: "Swan Bitcoin",
      category: "DCA purchase",
      account: "Cold Storage",
      tags: ["bitcoin", "dca"],
    },
    {
      daysAgo: 63,
      amount: "-0.01000000",
      currency: "BTC",
      description: "Monthly DCA",
      merchant: "Swan Bitcoin",
      category: "DCA purchase",
      account: "Cold Storage",
      tags: ["bitcoin", "dca"],
    },
    // Lightning spending
    {
      daysAgo: 1,
      amount: "-0.00012000",
      currency: "BTC",
      description: "Coffee",
      merchant: "Café Satoshi",
      category: "Coffee",
      account: "Lightning Wallet",
      tags: ["lightning"],
    },
    {
      daysAgo: 4,
      amount: "-0.00045000",
      currency: "BTC",
      description: "Lunch",
      merchant: "Burger Barn",
      category: "Restaurants",
      account: "Lightning Wallet",
      tags: ["lightning"],
    },
    {
      daysAgo: 8,
      amount: "-0.00018000",
      currency: "BTC",
      description: "Coffee",
      merchant: "Café Satoshi",
      category: "Coffee",
      account: "Lightning Wallet",
      tags: ["lightning"],
    },
    // On-chain fees
    {
      daysAgo: 3,
      amount: "-0.00003200",
      currency: "BTC",
      description: "On-chain sweep fee",
      category: "On-chain fees",
      account: "Cold Storage",
    },
    // Housing
    {
      daysAgo: 1,
      amount: "-2800.00",
      currency: "USD",
      description: "Rent",
      merchant: "Midtown Properties",
      category: "Rent / Mortgage",
      account: "Chase Checking",
    },
    {
      daysAgo: 31,
      amount: "-2800.00",
      currency: "USD",
      description: "Rent",
      merchant: "Midtown Properties",
      category: "Rent / Mortgage",
      account: "Chase Checking",
    },
    {
      daysAgo: 61,
      amount: "-2800.00",
      currency: "USD",
      description: "Rent",
      merchant: "Midtown Properties",
      category: "Rent / Mortgage",
      account: "Chase Checking",
    },
    // Utilities
    {
      daysAgo: 10,
      amount: "-145.00",
      currency: "USD",
      description: "Electric bill",
      merchant: "City Power",
      category: "Utilities",
      account: "Chase Checking",
    },
    {
      daysAgo: 40,
      amount: "-138.00",
      currency: "USD",
      description: "Electric bill",
      merchant: "City Power",
      category: "Utilities",
      account: "Chase Checking",
    },
    {
      daysAgo: 12,
      amount: "-85.00",
      currency: "USD",
      description: "Internet",
      merchant: "FiberNet",
      category: "Utilities",
      account: "Chase Checking",
    },
    // Food
    {
      daysAgo: 2,
      amount: "-167.00",
      currency: "USD",
      description: "Weekly groceries",
      merchant: "Whole Foods",
      category: "Groceries",
      account: "Chase Checking",
    },
    {
      daysAgo: 9,
      amount: "-143.00",
      currency: "USD",
      description: "Weekly groceries",
      merchant: "Whole Foods",
      category: "Groceries",
      account: "Chase Checking",
    },
    {
      daysAgo: 16,
      amount: "-158.00",
      currency: "USD",
      description: "Weekly groceries",
      merchant: "Trader Joe's",
      category: "Groceries",
      account: "Chase Checking",
    },
    {
      daysAgo: 6,
      amount: "-64.00",
      currency: "USD",
      description: "Family dinner",
      merchant: "Trattoria Roma",
      category: "Restaurants",
      account: "Chase Checking",
    },
    {
      daysAgo: 20,
      amount: "-48.00",
      currency: "USD",
      description: "Date night",
      merchant: "Sushi Zen",
      category: "Restaurants",
      account: "Chase Checking",
    },
    // Kids / Entertainment
    {
      daysAgo: 14,
      amount: "-35.00",
      currency: "USD",
      description: "School supplies",
      merchant: "Staples",
      category: "Shopping",
      account: "Chase Checking",
    },
    {
      daysAgo: 7,
      amount: "-15.99",
      currency: "USD",
      description: "Disney+",
      merchant: "Disney",
      category: "Streaming",
      account: "Chase Checking",
    },
    {
      daysAgo: 7,
      amount: "-13.99",
      currency: "USD",
      description: "Spotify Family",
      merchant: "Spotify",
      category: "Streaming",
      account: "Chase Checking",
    },
    {
      daysAgo: 22,
      amount: "-120.00",
      currency: "USD",
      description: "Kids soccer camp",
      merchant: "City Sports",
      category: "Events",
      account: "Chase Checking",
    },
    // Health
    {
      daysAgo: 18,
      amount: "-45.00",
      currency: "USD",
      description: "Doctor visit",
      merchant: "Family Medical",
      category: "Doctor",
      account: "Chase Checking",
    },
    {
      daysAgo: 11,
      amount: "-62.00",
      currency: "USD",
      description: "Gym membership",
      merchant: "24 Fitness",
      category: "Fitness",
      account: "Chase Checking",
    },
    // Transportation
    {
      daysAgo: 3,
      amount: "-68.00",
      currency: "USD",
      description: "Gas",
      merchant: "Shell",
      category: "Gas / Fuel",
      account: "Chase Checking",
    },
    {
      daysAgo: 33,
      amount: "-72.00",
      currency: "USD",
      description: "Gas",
      merchant: "Chevron",
      category: "Gas / Fuel",
      account: "Chase Checking",
    },
  ],
  goals: [
    {
      name: "1 Bitcoin stack",
      type: "save_up",
      targetAmount: "1.00000000",
      targetDate: date(-365 * -2),
      account: "Cold Storage",
    },
    {
      name: "Emergency fund (6 months)",
      type: "save_up",
      targetAmount: "45000.00",
      targetDate: date(-365),
      account: "Chase Savings",
    },
  ],
};

// ─── Family 2: The Anderson Family ────────────────────────────────────────────
// Traditional middle-class household. Teacher + nurse, 3 kids, mortgage.

const ANDERSON: DemoFamily = {
  id: "anderson",
  name: "The Anderson Family",
  tagline: "Traditional household · mortgage · 3 kids",
  description:
    "John (high school teacher) and Sarah (RN) manage a tight but steady budget. Mortgage, three kids in activities, and saving for a family vacation.",
  emoji: "🏠",
  accentColor: "#3b82f6",
  accounts: [
    {
      name: "Wells Fargo Checking",
      type: "checking",
      currency: "USD",
      institution: "Wells Fargo",
      balance: "4210.00",
    },
    {
      name: "Wells Fargo Savings",
      type: "savings",
      currency: "USD",
      institution: "Wells Fargo",
      balance: "12500.00",
    },
    {
      name: "Visa Credit Card",
      type: "credit",
      currency: "USD",
      institution: "Wells Fargo",
      balance: "-1840.00",
    },
  ],
  transactions: [
    // Income
    {
      daysAgo: 1,
      amount: "3200.00",
      currency: "USD",
      description: "Bi-weekly paycheck",
      merchant: "Riverside School District",
      category: "Salary",
      account: "Wells Fargo Checking",
    },
    {
      daysAgo: 15,
      amount: "3200.00",
      currency: "USD",
      description: "Bi-weekly paycheck",
      merchant: "Riverside School District",
      category: "Salary",
      account: "Wells Fargo Checking",
    },
    {
      daysAgo: 29,
      amount: "3200.00",
      currency: "USD",
      description: "Bi-weekly paycheck",
      merchant: "Riverside School District",
      category: "Salary",
      account: "Wells Fargo Checking",
    },
    {
      daysAgo: 43,
      amount: "3200.00",
      currency: "USD",
      description: "Bi-weekly paycheck",
      merchant: "Riverside School District",
      category: "Salary",
      account: "Wells Fargo Checking",
    },
    {
      daysAgo: 57,
      amount: "3200.00",
      currency: "USD",
      description: "Bi-weekly paycheck",
      merchant: "Riverside School District",
      category: "Salary",
      account: "Wells Fargo Checking",
    },
    {
      daysAgo: 71,
      amount: "3200.00",
      currency: "USD",
      description: "Bi-weekly paycheck",
      merchant: "Riverside School District",
      category: "Salary",
      account: "Wells Fargo Checking",
    },
    {
      daysAgo: 3,
      amount: "2900.00",
      currency: "USD",
      description: "Bi-weekly paycheck",
      merchant: "City General Hospital",
      category: "Salary",
      account: "Wells Fargo Checking",
    },
    {
      daysAgo: 17,
      amount: "2900.00",
      currency: "USD",
      description: "Bi-weekly paycheck",
      merchant: "City General Hospital",
      category: "Salary",
      account: "Wells Fargo Checking",
    },
    {
      daysAgo: 31,
      amount: "2900.00",
      currency: "USD",
      description: "Bi-weekly paycheck",
      merchant: "City General Hospital",
      category: "Salary",
      account: "Wells Fargo Checking",
    },
    {
      daysAgo: 45,
      amount: "2900.00",
      currency: "USD",
      description: "Bi-weekly paycheck",
      merchant: "City General Hospital",
      category: "Salary",
      account: "Wells Fargo Checking",
    },
    {
      daysAgo: 59,
      amount: "2900.00",
      currency: "USD",
      description: "Bi-weekly paycheck",
      merchant: "City General Hospital",
      category: "Salary",
      account: "Wells Fargo Checking",
    },
    {
      daysAgo: 73,
      amount: "2900.00",
      currency: "USD",
      description: "Bi-weekly paycheck",
      merchant: "City General Hospital",
      category: "Salary",
      account: "Wells Fargo Checking",
    },
    // Mortgage
    {
      daysAgo: 1,
      amount: "-1780.00",
      currency: "USD",
      description: "Mortgage payment",
      merchant: "First National Bank",
      category: "Rent / Mortgage",
      account: "Wells Fargo Checking",
    },
    {
      daysAgo: 31,
      amount: "-1780.00",
      currency: "USD",
      description: "Mortgage payment",
      merchant: "First National Bank",
      category: "Rent / Mortgage",
      account: "Wells Fargo Checking",
    },
    {
      daysAgo: 61,
      amount: "-1780.00",
      currency: "USD",
      description: "Mortgage payment",
      merchant: "First National Bank",
      category: "Rent / Mortgage",
      account: "Wells Fargo Checking",
    },
    // Utilities
    {
      daysAgo: 8,
      amount: "-210.00",
      currency: "USD",
      description: "Electric + gas",
      merchant: "Suburban Utilities",
      category: "Utilities",
      account: "Wells Fargo Checking",
    },
    {
      daysAgo: 38,
      amount: "-195.00",
      currency: "USD",
      description: "Electric + gas",
      merchant: "Suburban Utilities",
      category: "Utilities",
      account: "Wells Fargo Checking",
    },
    {
      daysAgo: 68,
      amount: "-220.00",
      currency: "USD",
      description: "Electric + gas",
      merchant: "Suburban Utilities",
      category: "Utilities",
      account: "Wells Fargo Checking",
    },
    {
      daysAgo: 10,
      amount: "-89.00",
      currency: "USD",
      description: "Internet + cable",
      merchant: "Comcast",
      category: "Utilities",
      account: "Wells Fargo Checking",
    },
    // Groceries
    {
      daysAgo: 2,
      amount: "-198.00",
      currency: "USD",
      description: "Grocery run",
      merchant: "Kroger",
      category: "Groceries",
      account: "Visa Credit Card",
    },
    {
      daysAgo: 9,
      amount: "-212.00",
      currency: "USD",
      description: "Grocery run",
      merchant: "Kroger",
      category: "Groceries",
      account: "Visa Credit Card",
    },
    {
      daysAgo: 16,
      amount: "-187.00",
      currency: "USD",
      description: "Grocery run",
      merchant: "Walmart",
      category: "Groceries",
      account: "Visa Credit Card",
    },
    {
      daysAgo: 23,
      amount: "-205.00",
      currency: "USD",
      description: "Grocery run",
      merchant: "Kroger",
      category: "Groceries",
      account: "Visa Credit Card",
    },
    {
      daysAgo: 30,
      amount: "-192.00",
      currency: "USD",
      description: "Grocery run",
      merchant: "Kroger",
      category: "Groceries",
      account: "Visa Credit Card",
    },
    // Kids activities
    {
      daysAgo: 5,
      amount: "-85.00",
      currency: "USD",
      description: "Soccer registration",
      merchant: "Valley Youth Sports",
      category: "Events",
      account: "Wells Fargo Checking",
    },
    {
      daysAgo: 20,
      amount: "-60.00",
      currency: "USD",
      description: "Piano lessons",
      merchant: "Music Academy",
      category: "Events",
      account: "Wells Fargo Checking",
    },
    {
      daysAgo: 50,
      amount: "-60.00",
      currency: "USD",
      description: "Piano lessons",
      merchant: "Music Academy",
      category: "Events",
      account: "Wells Fargo Checking",
    },
    {
      daysAgo: 12,
      amount: "-45.00",
      currency: "USD",
      description: "School fundraiser",
      merchant: "Riverside Elementary",
      category: "Gifts received",
      account: "Wells Fargo Checking",
      memo: "Actually paid out — bake sale supplies",
    },
    // Dining
    {
      daysAgo: 6,
      amount: "-68.00",
      currency: "USD",
      description: "Family dinner",
      merchant: "Olive Garden",
      category: "Restaurants",
      account: "Visa Credit Card",
    },
    {
      daysAgo: 25,
      amount: "-42.00",
      currency: "USD",
      description: "Pizza night",
      merchant: "Domino's",
      category: "Restaurants",
      account: "Visa Credit Card",
    },
    {
      daysAgo: 55,
      amount: "-55.00",
      currency: "USD",
      description: "Anniversary dinner",
      merchant: "The Grillhouse",
      category: "Restaurants",
      account: "Visa Credit Card",
    },
    // Transportation
    {
      daysAgo: 4,
      amount: "-82.00",
      currency: "USD",
      description: "Gas",
      merchant: "BP",
      category: "Gas / Fuel",
      account: "Visa Credit Card",
    },
    {
      daysAgo: 34,
      amount: "-78.00",
      currency: "USD",
      description: "Gas",
      merchant: "Shell",
      category: "Gas / Fuel",
      account: "Visa Credit Card",
    },
    {
      daysAgo: 64,
      amount: "-91.00",
      currency: "USD",
      description: "Gas",
      merchant: "Exxon",
      category: "Gas / Fuel",
      account: "Visa Credit Card",
    },
    {
      daysAgo: 22,
      amount: "-320.00",
      currency: "USD",
      description: "Oil change + tires",
      merchant: "Jiffy Lube",
      category: "Vehicle maintenance",
      account: "Wells Fargo Checking",
    },
    // Health
    {
      daysAgo: 15,
      amount: "-35.00",
      currency: "USD",
      description: "Prescription refill",
      merchant: "CVS Pharmacy",
      category: "Pharmacy",
      account: "Visa Credit Card",
    },
    {
      daysAgo: 28,
      amount: "-120.00",
      currency: "USD",
      description: "Pediatrician visit",
      merchant: "Kids First Clinic",
      category: "Doctor",
      account: "Wells Fargo Checking",
    },
    // Savings transfer
    {
      daysAgo: 2,
      amount: "-300.00",
      currency: "USD",
      description: "Transfer to savings",
      category: "Savings transfer",
      account: "Wells Fargo Checking",
    },
    {
      daysAgo: 32,
      amount: "-300.00",
      currency: "USD",
      description: "Transfer to savings",
      category: "Savings transfer",
      account: "Wells Fargo Checking",
    },
    {
      daysAgo: 62,
      amount: "-300.00",
      currency: "USD",
      description: "Transfer to savings",
      category: "Savings transfer",
      account: "Wells Fargo Checking",
    },
  ],
  goals: [
    {
      name: "Disney World vacation",
      type: "save_up",
      targetAmount: "5000.00",
      targetDate: date(-180),
      account: "Wells Fargo Savings",
    },
    {
      name: "Emergency fund",
      type: "save_up",
      targetAmount: "18000.00",
      targetDate: date(-270),
      account: "Wells Fargo Savings",
    },
    {
      name: "Pay off Visa card",
      type: "pay_down",
      targetAmount: "0.00",
      targetDate: date(-90),
      account: "Visa Credit Card",
    },
  ],
};

// ─── Family 3: The Reyes Family ───────────────────────────────────────────────
// Young professional couple. High income, high lifestyle — dining, travel, subscriptions.

const REYES: DemoFamily = {
  id: "reyes",
  name: "The Reyes Family",
  tagline: "Young professionals · dual income · travel lovers",
  description:
    "Carlos (marketing director) and Ana (senior UX designer) live in the city, eat out 4× a week, and travel every quarter. Saving for a down payment.",
  emoji: "✈️",
  accentColor: "#8b5cf6",
  accounts: [
    {
      name: "Chase Checking",
      type: "checking",
      currency: "USD",
      institution: "Chase",
      balance: "15600.00",
    },
    {
      name: "High-yield Savings",
      type: "savings",
      currency: "USD",
      institution: "Marcus by Goldman",
      balance: "41000.00",
    },
    {
      name: "Amex Platinum",
      type: "credit",
      currency: "USD",
      institution: "American Express",
      balance: "-4200.00",
    },
    {
      name: "Bitcoin Wallet",
      type: "bitcoin",
      currency: "BTC",
      institution: "Strike",
      balance: "0.05000000",
    },
  ],
  transactions: [
    // Income
    {
      daysAgo: 1,
      amount: "5500.00",
      currency: "USD",
      description: "Monthly salary",
      merchant: "Apex Marketing Group",
      category: "Salary",
      account: "Chase Checking",
    },
    {
      daysAgo: 31,
      amount: "5500.00",
      currency: "USD",
      description: "Monthly salary",
      merchant: "Apex Marketing Group",
      category: "Salary",
      account: "Chase Checking",
    },
    {
      daysAgo: 61,
      amount: "5500.00",
      currency: "USD",
      description: "Monthly salary",
      merchant: "Apex Marketing Group",
      category: "Salary",
      account: "Chase Checking",
    },
    {
      daysAgo: 3,
      amount: "5800.00",
      currency: "USD",
      description: "Monthly salary",
      merchant: "Forma Studio",
      category: "Salary",
      account: "Chase Checking",
    },
    {
      daysAgo: 33,
      amount: "5800.00",
      currency: "USD",
      description: "Monthly salary",
      merchant: "Forma Studio",
      category: "Salary",
      account: "Chase Checking",
    },
    {
      daysAgo: 63,
      amount: "5800.00",
      currency: "USD",
      description: "Monthly salary",
      merchant: "Forma Studio",
      category: "Salary",
      account: "Chase Checking",
    },
    // Rent
    {
      daysAgo: 1,
      amount: "-3200.00",
      currency: "USD",
      description: "Rent",
      merchant: "Skyline Apartments",
      category: "Rent / Mortgage",
      account: "Chase Checking",
    },
    {
      daysAgo: 31,
      amount: "-3200.00",
      currency: "USD",
      description: "Rent",
      merchant: "Skyline Apartments",
      category: "Rent / Mortgage",
      account: "Chase Checking",
    },
    {
      daysAgo: 61,
      amount: "-3200.00",
      currency: "USD",
      description: "Rent",
      merchant: "Skyline Apartments",
      category: "Rent / Mortgage",
      account: "Chase Checking",
    },
    // Dining (heavy)
    {
      daysAgo: 1,
      amount: "-95.00",
      currency: "USD",
      description: "Date night",
      merchant: "Nobu",
      category: "Restaurants",
      account: "Amex Platinum",
    },
    {
      daysAgo: 4,
      amount: "-62.00",
      currency: "USD",
      description: "Dinner with friends",
      merchant: "Uchi",
      category: "Restaurants",
      account: "Amex Platinum",
    },
    {
      daysAgo: 7,
      amount: "-44.00",
      currency: "USD",
      description: "Brunch",
      merchant: "Perla's",
      category: "Restaurants",
      account: "Amex Platinum",
    },
    {
      daysAgo: 10,
      amount: "-78.00",
      currency: "USD",
      description: "Business dinner",
      merchant: "The Capital Grille",
      category: "Restaurants",
      account: "Amex Platinum",
    },
    {
      daysAgo: 13,
      amount: "-38.00",
      currency: "USD",
      description: "Casual dinner",
      merchant: "Torchy's Tacos",
      category: "Restaurants",
      account: "Amex Platinum",
    },
    {
      daysAgo: 3,
      amount: "-8.50",
      currency: "USD",
      description: "Morning coffee",
      merchant: "Blue Bottle",
      category: "Coffee",
      account: "Amex Platinum",
    },
    {
      daysAgo: 6,
      amount: "-9.00",
      currency: "USD",
      description: "Coffee",
      merchant: "Blue Bottle",
      category: "Coffee",
      account: "Amex Platinum",
    },
    {
      daysAgo: 9,
      amount: "-8.50",
      currency: "USD",
      description: "Coffee",
      merchant: "Blue Bottle",
      category: "Coffee",
      account: "Amex Platinum",
    },
    // Travel
    {
      daysAgo: 42,
      amount: "-680.00",
      currency: "USD",
      description: "Flights to NYC",
      merchant: "Delta Airlines",
      category: "Flights",
      account: "Amex Platinum",
      tags: ["travel", "nyc"],
    },
    {
      daysAgo: 40,
      amount: "-420.00",
      currency: "USD",
      description: "Hotel — NYC",
      merchant: "The Standard Hotel",
      category: "Hotels",
      account: "Amex Platinum",
      tags: ["travel", "nyc"],
    },
    {
      daysAgo: 38,
      amount: "-185.00",
      currency: "USD",
      description: "Meals NYC trip",
      merchant: "Various",
      category: "Meals away",
      account: "Amex Platinum",
      tags: ["travel", "nyc"],
    },
    {
      daysAgo: 72,
      amount: "-1240.00",
      currency: "USD",
      description: "Flights to Mexico City",
      merchant: "United Airlines",
      category: "Flights",
      account: "Amex Platinum",
      tags: ["travel", "mexico"],
    },
    {
      daysAgo: 70,
      amount: "-380.00",
      currency: "USD",
      description: "Hotel — CDMX",
      merchant: "Hotel Condesa",
      category: "Hotels",
      account: "Amex Platinum",
      tags: ["travel", "mexico"],
    },
    // Subscriptions
    {
      daysAgo: 5,
      amount: "-18.00",
      currency: "USD",
      description: "Netflix",
      merchant: "Netflix",
      category: "Streaming",
      account: "Amex Platinum",
    },
    {
      daysAgo: 5,
      amount: "-15.99",
      currency: "USD",
      description: "Spotify",
      merchant: "Spotify",
      category: "Streaming",
      account: "Amex Platinum",
    },
    {
      daysAgo: 5,
      amount: "-9.99",
      currency: "USD",
      description: "ChatGPT Plus",
      merchant: "OpenAI",
      category: "Streaming",
      account: "Amex Platinum",
    },
    {
      daysAgo: 5,
      amount: "-14.99",
      currency: "USD",
      description: "Apple One",
      merchant: "Apple",
      category: "Streaming",
      account: "Amex Platinum",
    },
    {
      daysAgo: 5,
      amount: "-99.00",
      currency: "USD",
      description: "Gym membership",
      merchant: "Equinox",
      category: "Fitness",
      account: "Amex Platinum",
    },
    // Shopping
    {
      daysAgo: 16,
      amount: "-340.00",
      currency: "USD",
      description: "New outfit",
      merchant: "Nordstrom",
      category: "Clothing",
      account: "Amex Platinum",
    },
    {
      daysAgo: 30,
      amount: "-189.00",
      currency: "USD",
      description: "AirPods Pro",
      merchant: "Apple Store",
      category: "Electronics",
      account: "Amex Platinum",
    },
    {
      daysAgo: 50,
      amount: "-220.00",
      currency: "USD",
      description: "Home decor",
      merchant: "West Elm",
      category: "Home goods",
      account: "Amex Platinum",
    },
    // Groceries (less than Anderson — they eat out more)
    {
      daysAgo: 3,
      amount: "-95.00",
      currency: "USD",
      description: "Groceries",
      merchant: "Whole Foods",
      category: "Groceries",
      account: "Amex Platinum",
    },
    {
      daysAgo: 17,
      amount: "-88.00",
      currency: "USD",
      description: "Groceries",
      merchant: "Whole Foods",
      category: "Groceries",
      account: "Amex Platinum",
    },
    {
      daysAgo: 31,
      amount: "-102.00",
      currency: "USD",
      description: "Groceries",
      merchant: "Whole Foods",
      category: "Groceries",
      account: "Amex Platinum",
    },
    // Bitcoin DCA
    {
      daysAgo: 5,
      amount: "-0.00500000",
      currency: "BTC",
      description: "Weekly Bitcoin purchase",
      merchant: "Strike",
      category: "DCA purchase",
      account: "Bitcoin Wallet",
      tags: ["bitcoin"],
    },
    {
      daysAgo: 12,
      amount: "-0.00500000",
      currency: "BTC",
      description: "Weekly Bitcoin purchase",
      merchant: "Strike",
      category: "DCA purchase",
      account: "Bitcoin Wallet",
      tags: ["bitcoin"],
    },
    {
      daysAgo: 19,
      amount: "-0.00500000",
      currency: "BTC",
      description: "Weekly Bitcoin purchase",
      merchant: "Strike",
      category: "DCA purchase",
      account: "Bitcoin Wallet",
      tags: ["bitcoin"],
    },
    // Savings transfer
    {
      daysAgo: 2,
      amount: "-2000.00",
      currency: "USD",
      description: "Down payment fund",
      category: "Savings transfer",
      account: "Chase Checking",
      memo: "Monthly transfer to HYSA",
    },
    {
      daysAgo: 32,
      amount: "-2000.00",
      currency: "USD",
      description: "Down payment fund",
      category: "Savings transfer",
      account: "Chase Checking",
    },
    {
      daysAgo: 62,
      amount: "-2000.00",
      currency: "USD",
      description: "Down payment fund",
      category: "Savings transfer",
      account: "Chase Checking",
    },
  ],
  goals: [
    {
      name: "House down payment",
      type: "save_up",
      targetAmount: "100000.00",
      targetDate: date(-365 * -2),
      account: "High-yield Savings",
    },
    {
      name: "Honeymoon — Japan",
      type: "save_up",
      targetAmount: "8000.00",
      targetDate: date(-365),
      account: "High-yield Savings",
    },
    {
      name: "Pay off Amex balance",
      type: "pay_down",
      targetAmount: "0.00",
      targetDate: date(-60),
      account: "Amex Platinum",
    },
  ],
};

export const DEMO_FAMILIES: DemoFamily[] = [NAKAMOTO, ANDERSON, REYES];
