/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletsRouteImport } from './routes/wallets'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SelfHostRouteImport } from './routes/self-host'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyChangelogRouteImport } from './routes/privacy-changelog'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LandingClassicRouteImport } from './routes/landing-classic'
import { Route as JoinRouteImport } from './routes/join'
import { Route as HouseholdsRouteImport } from './routes/households'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CashFlowRouteImport } from './routes/cash-flow'
import { Route as BudgetsRouteImport } from './routes/budgets'
import { Route as BitcoinRouteImport } from './routes/bitcoin'
import { Route as BetaRouteImport } from './routes/beta'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as WalletsIdRouteImport } from './routes/wallets.$id'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as SettingsRulesRouteImport } from './routes/settings.rules'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsPreferencesRouteImport } from './routes/settings.preferences'
import { Route as SettingsImportExportRouteImport } from './routes/settings.import-export'
import { Route as SettingsHouseholdSecurityRouteImport } from './routes/settings.household-security'
import { Route as SettingsHouseholdRouteImport } from './routes/settings.household'
import { Route as SettingsDemoRouteImport } from './routes/settings.demo'
import { Route as SettingsCategoriesRouteImport } from './routes/settings.categories'
import { Route as SettingsAboutRouteImport } from './routes/settings.about'
import { Route as GoalsIdRouteImport } from './routes/goals.$id'
import { Route as AccountsIdRouteImport } from './routes/accounts.$id'
import { Route as ApiPublicAiManifestDotjsonRouteImport } from './routes/api.public.ai.manifest[.]json'

const WalletsRoute = WalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfHostRoute = SelfHostRouteImport.update({
  id: '/self-host',
  path: '/self-host',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyChangelogRoute = PrivacyChangelogRouteImport.update({
  id: '/privacy-changelog',
  path: '/privacy-changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingClassicRoute = LandingClassicRouteImport.update({
  id: '/landing-classic',
  path: '/landing-classic',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdsRoute = HouseholdsRouteImport.update({
  id: '/households',
  path: '/households',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CashFlowRoute = CashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsRoute = BudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const BitcoinRoute = BitcoinRouteImport.update({
  id: '/bitcoin',
  path: '/bitcoin',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaRoute = BetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const WalletsIdRoute = WalletsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WalletsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRulesRoute = SettingsRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsImportExportRoute = SettingsImportExportRouteImport.update({
  id: '/import-export',
  path: '/import-export',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsHouseholdSecurityRoute =
  SettingsHouseholdSecurityRouteImport.update({
    id: '/household-security',
    path: '/household-security',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsHouseholdRoute = SettingsHouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDemoRoute = SettingsDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCategoriesRoute = SettingsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const GoalsIdRoute = GoalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GoalsRoute,
} as any)
const AccountsIdRoute = AccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccountsRoute,
} as any)
const ApiPublicAiManifestDotjsonRoute =
  ApiPublicAiManifestDotjsonRouteImport.update({
    id: '/api/public/ai/manifest.json',
    path: '/api/public/ai/manifest.json',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/beta': typeof BetaRoute
  '/bitcoin': typeof BitcoinRoute
  '/budgets': typeof BudgetsRoute
  '/cash-flow': typeof CashFlowRoute
  '/changelog': typeof ChangelogRoute
  '/compare': typeof CompareRoute
  '/connections': typeof ConnectionsRoute
  '/dashboard': typeof DashboardRoute
  '/enterprise': typeof EnterpriseRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/goals': typeof GoalsRouteWithChildren
  '/households': typeof HouseholdsRoute
  '/join': typeof JoinRoute
  '/landing-classic': typeof LandingClassicRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-changelog': typeof PrivacyChangelogRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/self-host': typeof SelfHostRoute
  '/settings': typeof SettingsRouteWithChildren
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/wallets': typeof WalletsRouteWithChildren
  '/accounts/$id': typeof AccountsIdRoute
  '/goals/$id': typeof GoalsIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/demo': typeof SettingsDemoRoute
  '/settings/household': typeof SettingsHouseholdRoute
  '/settings/household-security': typeof SettingsHouseholdSecurityRoute
  '/settings/import-export': typeof SettingsImportExportRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/rules': typeof SettingsRulesRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/wallets/$id': typeof WalletsIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/public/ai/manifest.json': typeof ApiPublicAiManifestDotjsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/beta': typeof BetaRoute
  '/bitcoin': typeof BitcoinRoute
  '/budgets': typeof BudgetsRoute
  '/cash-flow': typeof CashFlowRoute
  '/changelog': typeof ChangelogRoute
  '/compare': typeof CompareRoute
  '/connections': typeof ConnectionsRoute
  '/dashboard': typeof DashboardRoute
  '/enterprise': typeof EnterpriseRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/goals': typeof GoalsRouteWithChildren
  '/households': typeof HouseholdsRoute
  '/join': typeof JoinRoute
  '/landing-classic': typeof LandingClassicRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-changelog': typeof PrivacyChangelogRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/self-host': typeof SelfHostRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/wallets': typeof WalletsRouteWithChildren
  '/accounts/$id': typeof AccountsIdRoute
  '/goals/$id': typeof GoalsIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/demo': typeof SettingsDemoRoute
  '/settings/household': typeof SettingsHouseholdRoute
  '/settings/household-security': typeof SettingsHouseholdSecurityRoute
  '/settings/import-export': typeof SettingsImportExportRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/rules': typeof SettingsRulesRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/wallets/$id': typeof WalletsIdRoute
  '/settings': typeof SettingsIndexRoute
  '/api/public/ai/manifest.json': typeof ApiPublicAiManifestDotjsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/beta': typeof BetaRoute
  '/bitcoin': typeof BitcoinRoute
  '/budgets': typeof BudgetsRoute
  '/cash-flow': typeof CashFlowRoute
  '/changelog': typeof ChangelogRoute
  '/compare': typeof CompareRoute
  '/connections': typeof ConnectionsRoute
  '/dashboard': typeof DashboardRoute
  '/enterprise': typeof EnterpriseRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/goals': typeof GoalsRouteWithChildren
  '/households': typeof HouseholdsRoute
  '/join': typeof JoinRoute
  '/landing-classic': typeof LandingClassicRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-changelog': typeof PrivacyChangelogRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/self-host': typeof SelfHostRoute
  '/settings': typeof SettingsRouteWithChildren
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/wallets': typeof WalletsRouteWithChildren
  '/accounts/$id': typeof AccountsIdRoute
  '/goals/$id': typeof GoalsIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/demo': typeof SettingsDemoRoute
  '/settings/household': typeof SettingsHouseholdRoute
  '/settings/household-security': typeof SettingsHouseholdSecurityRoute
  '/settings/import-export': typeof SettingsImportExportRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/rules': typeof SettingsRulesRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/wallets/$id': typeof WalletsIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/public/ai/manifest.json': typeof ApiPublicAiManifestDotjsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accounts'
    | '/ai'
    | '/auth'
    | '/beta'
    | '/bitcoin'
    | '/budgets'
    | '/cash-flow'
    | '/changelog'
    | '/compare'
    | '/connections'
    | '/dashboard'
    | '/enterprise'
    | '/faq'
    | '/features'
    | '/goals'
    | '/households'
    | '/join'
    | '/landing-classic'
    | '/pricing'
    | '/privacy'
    | '/privacy-changelog'
    | '/reset-password'
    | '/security'
    | '/self-host'
    | '/settings'
    | '/terms'
    | '/transactions'
    | '/wallets'
    | '/accounts/$id'
    | '/goals/$id'
    | '/settings/about'
    | '/settings/categories'
    | '/settings/demo'
    | '/settings/household'
    | '/settings/household-security'
    | '/settings/import-export'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/rules'
    | '/settings/security'
    | '/wallets/$id'
    | '/settings/'
    | '/api/public/ai/manifest.json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accounts'
    | '/ai'
    | '/auth'
    | '/beta'
    | '/bitcoin'
    | '/budgets'
    | '/cash-flow'
    | '/changelog'
    | '/compare'
    | '/connections'
    | '/dashboard'
    | '/enterprise'
    | '/faq'
    | '/features'
    | '/goals'
    | '/households'
    | '/join'
    | '/landing-classic'
    | '/pricing'
    | '/privacy'
    | '/privacy-changelog'
    | '/reset-password'
    | '/security'
    | '/self-host'
    | '/terms'
    | '/transactions'
    | '/wallets'
    | '/accounts/$id'
    | '/goals/$id'
    | '/settings/about'
    | '/settings/categories'
    | '/settings/demo'
    | '/settings/household'
    | '/settings/household-security'
    | '/settings/import-export'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/rules'
    | '/settings/security'
    | '/wallets/$id'
    | '/settings'
    | '/api/public/ai/manifest.json'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accounts'
    | '/ai'
    | '/auth'
    | '/beta'
    | '/bitcoin'
    | '/budgets'
    | '/cash-flow'
    | '/changelog'
    | '/compare'
    | '/connections'
    | '/dashboard'
    | '/enterprise'
    | '/faq'
    | '/features'
    | '/goals'
    | '/households'
    | '/join'
    | '/landing-classic'
    | '/pricing'
    | '/privacy'
    | '/privacy-changelog'
    | '/reset-password'
    | '/security'
    | '/self-host'
    | '/settings'
    | '/terms'
    | '/transactions'
    | '/wallets'
    | '/accounts/$id'
    | '/goals/$id'
    | '/settings/about'
    | '/settings/categories'
    | '/settings/demo'
    | '/settings/household'
    | '/settings/household-security'
    | '/settings/import-export'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/rules'
    | '/settings/security'
    | '/wallets/$id'
    | '/settings/'
    | '/api/public/ai/manifest.json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountsRoute: typeof AccountsRouteWithChildren
  AiRoute: typeof AiRoute
  AuthRoute: typeof AuthRoute
  BetaRoute: typeof BetaRoute
  BitcoinRoute: typeof BitcoinRoute
  BudgetsRoute: typeof BudgetsRoute
  CashFlowRoute: typeof CashFlowRoute
  ChangelogRoute: typeof ChangelogRoute
  CompareRoute: typeof CompareRoute
  ConnectionsRoute: typeof ConnectionsRoute
  DashboardRoute: typeof DashboardRoute
  EnterpriseRoute: typeof EnterpriseRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  GoalsRoute: typeof GoalsRouteWithChildren
  HouseholdsRoute: typeof HouseholdsRoute
  JoinRoute: typeof JoinRoute
  LandingClassicRoute: typeof LandingClassicRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyChangelogRoute: typeof PrivacyChangelogRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  SelfHostRoute: typeof SelfHostRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TermsRoute: typeof TermsRoute
  TransactionsRoute: typeof TransactionsRoute
  WalletsRoute: typeof WalletsRouteWithChildren
  ApiPublicAiManifestDotjsonRoute: typeof ApiPublicAiManifestDotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallets': {
      id: '/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof WalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-host': {
      id: '/self-host'
      path: '/self-host'
      fullPath: '/self-host'
      preLoaderRoute: typeof SelfHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-changelog': {
      id: '/privacy-changelog'
      path: '/privacy-changelog'
      fullPath: '/privacy-changelog'
      preLoaderRoute: typeof PrivacyChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-classic': {
      id: '/landing-classic'
      path: '/landing-classic'
      fullPath: '/landing-classic'
      preLoaderRoute: typeof LandingClassicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/households': {
      id: '/households'
      path: '/households'
      fullPath: '/households'
      preLoaderRoute: typeof HouseholdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-flow': {
      id: '/cash-flow'
      path: '/cash-flow'
      fullPath: '/cash-flow'
      preLoaderRoute: typeof CashFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bitcoin': {
      id: '/bitcoin'
      path: '/bitcoin'
      fullPath: '/bitcoin'
      preLoaderRoute: typeof BitcoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta': {
      id: '/beta'
      path: '/beta'
      fullPath: '/beta'
      preLoaderRoute: typeof BetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/wallets/$id': {
      id: '/wallets/$id'
      path: '/$id'
      fullPath: '/wallets/$id'
      preLoaderRoute: typeof WalletsIdRouteImport
      parentRoute: typeof WalletsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/rules': {
      id: '/settings/rules'
      path: '/rules'
      fullPath: '/settings/rules'
      preLoaderRoute: typeof SettingsRulesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/import-export': {
      id: '/settings/import-export'
      path: '/import-export'
      fullPath: '/settings/import-export'
      preLoaderRoute: typeof SettingsImportExportRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/household-security': {
      id: '/settings/household-security'
      path: '/household-security'
      fullPath: '/settings/household-security'
      preLoaderRoute: typeof SettingsHouseholdSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/household': {
      id: '/settings/household'
      path: '/household'
      fullPath: '/settings/household'
      preLoaderRoute: typeof SettingsHouseholdRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/demo': {
      id: '/settings/demo'
      path: '/demo'
      fullPath: '/settings/demo'
      preLoaderRoute: typeof SettingsDemoRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/categories': {
      id: '/settings/categories'
      path: '/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof SettingsCategoriesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/goals/$id': {
      id: '/goals/$id'
      path: '/$id'
      fullPath: '/goals/$id'
      preLoaderRoute: typeof GoalsIdRouteImport
      parentRoute: typeof GoalsRoute
    }
    '/accounts/$id': {
      id: '/accounts/$id'
      path: '/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AccountsIdRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/api/public/ai/manifest.json': {
      id: '/api/public/ai/manifest.json'
      path: '/api/public/ai/manifest.json'
      fullPath: '/api/public/ai/manifest.json'
      preLoaderRoute: typeof ApiPublicAiManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountsRouteChildren {
  AccountsIdRoute: typeof AccountsIdRoute
}

const AccountsRouteChildren: AccountsRouteChildren = {
  AccountsIdRoute: AccountsIdRoute,
}

const AccountsRouteWithChildren = AccountsRoute._addFileChildren(
  AccountsRouteChildren,
)

interface GoalsRouteChildren {
  GoalsIdRoute: typeof GoalsIdRoute
}

const GoalsRouteChildren: GoalsRouteChildren = {
  GoalsIdRoute: GoalsIdRoute,
}

const GoalsRouteWithChildren = GoalsRoute._addFileChildren(GoalsRouteChildren)

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsCategoriesRoute: typeof SettingsCategoriesRoute
  SettingsDemoRoute: typeof SettingsDemoRoute
  SettingsHouseholdRoute: typeof SettingsHouseholdRoute
  SettingsHouseholdSecurityRoute: typeof SettingsHouseholdSecurityRoute
  SettingsImportExportRoute: typeof SettingsImportExportRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsRulesRoute: typeof SettingsRulesRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsCategoriesRoute: SettingsCategoriesRoute,
  SettingsDemoRoute: SettingsDemoRoute,
  SettingsHouseholdRoute: SettingsHouseholdRoute,
  SettingsHouseholdSecurityRoute: SettingsHouseholdSecurityRoute,
  SettingsImportExportRoute: SettingsImportExportRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsRulesRoute: SettingsRulesRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface WalletsRouteChildren {
  WalletsIdRoute: typeof WalletsIdRoute
}

const WalletsRouteChildren: WalletsRouteChildren = {
  WalletsIdRoute: WalletsIdRoute,
}

const WalletsRouteWithChildren =
  WalletsRoute._addFileChildren(WalletsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountsRoute: AccountsRouteWithChildren,
  AiRoute: AiRoute,
  AuthRoute: AuthRoute,
  BetaRoute: BetaRoute,
  BitcoinRoute: BitcoinRoute,
  BudgetsRoute: BudgetsRoute,
  CashFlowRoute: CashFlowRoute,
  ChangelogRoute: ChangelogRoute,
  CompareRoute: CompareRoute,
  ConnectionsRoute: ConnectionsRoute,
  DashboardRoute: DashboardRoute,
  EnterpriseRoute: EnterpriseRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  GoalsRoute: GoalsRouteWithChildren,
  HouseholdsRoute: HouseholdsRoute,
  JoinRoute: JoinRoute,
  LandingClassicRoute: LandingClassicRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyChangelogRoute: PrivacyChangelogRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  SelfHostRoute: SelfHostRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TermsRoute: TermsRoute,
  TransactionsRoute: TransactionsRoute,
  WalletsRoute: WalletsRouteWithChildren,
  ApiPublicAiManifestDotjsonRoute: ApiPublicAiManifestDotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
