-- THROWAWAY, do not merge. Proves the new cron-calling-role revoke scan in
-- scripts/check-definer-grant-migrations.sh (OWM-T0635 step 7) actually
-- fires. This file is never applied to any database: the PR-scan CI job
-- only diffs migration text, it does not run SQL. Removed in the next
-- commit on this branch once the red run is captured.
-- Revoke statement removed: this proves the definer-grant-migrations scan
-- job goes GREEN again once the offending statement is gone. See the RED
-- run at commit b0be24e3 for the paired proof. No SQL executes here.
