-- SUPERSEDED, INTENTIONALLY EMPTY. Do not add statements to this file.
--
-- This version originally created public.invite_codes and the two invite
-- code functions. It was replaced before it was ever applied by
-- 20260709120000_invite_codes.sql, which is the recorded, authoritative
-- version of that schema. This file is not in any ledger.
--
-- It is emptied rather than left in place because its final statement
-- granted execute on public.redeem_invite_code(text) to anon, and
-- 20260720000000_restrict_redeem_invite_code_to_authenticated.sql later
-- narrows that same function to authenticated only. Running this file
-- after that one would silently re-widen the grant, with nothing
-- afterwards to narrow it again.
--
-- Current source of truth for the invite code surface:
--   20260709120000_invite_codes.sql                          (table + functions)
--   20260720000000_restrict_redeem_invite_code_to_authenticated.sql  (grant)
